version: '3.4'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      network: host
      target: app
    command:
      bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8080'
    volumes:
      - ./src:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    expose:
      - "5432"
    env_file:
      - .env
